"""The `standard` route: every keyed chat deployment behind one model name.

A client that does not care which free model answers sends `model:
"standard"`. The route is generated at render time from the deployments
that survive upstream's provider filter: each chat deployment is copied
under `model_name: standard` with a unique `litellm_params.order`. LiteLLM
routes to the lowest order first and, when that level fails, walks up
order by order (order-based fallbacks, bounded by `max_fallbacks`), so the
request tries every provider in turn until one answers.

Priority follows docs/adr/0001-fork-conventions.md. A provider key that
appears in `.env` puts that provider's models into the chain on the next
render; nothing has to be edited by hand.
"""
from __future__ import annotations

ROUTE_NAME = "standard"

# Provider priority for the `standard` chain, first = tried first. The
# first five are the operator's call; the rest are keyed providers ordered
# by their free-tier request budget (providers_config.py rpm, ties
# alphabetical); anonymous tiers go last because their quota is shared by
# everyone. Every provider in providers_config.PROVIDERS must be listed
# (tests/test_standard_route.py) so a new upstream provider gets a
# deliberate slot instead of a silent one.
PROVIDER_PRIORITY: tuple[str, ...] = (
    "google-ai",      # Gemini: generous free tier, strong json_schema support
    "groq",           # fast, small daily budget
    "openrouter",     # many free models behind one key
    "mistral",
    "nvidia",
    "cerebras",       # rpm 30
    "huggingface",    # rpm 30
    "cohere",         # rpm 20
    "cloudflare",     # rpm 10
    "opencode-zen",   # rpm 10
    "poolside",       # rpm 10
    "hetzner",        # rpm 5
    "zai",            # rpm 1
    "elevenlabs",     # no chat models today; listed so the set stays complete
    "llm7io",         # anonymous tier, 10 rpm shared across all callers
    "ovhcloud",       # anonymous tier; joins the chain only with a key
)

_RANK = {name: i for i, name in enumerate(PROVIDER_PRIORITY)}


def deployment_key(block: dict) -> tuple[str, str]:
    """What makes two deployments the same backend: model id + host."""
    return block["model_id"], block.get("api_base", "")


def has_key(provider: str, env: dict[str, str], providers: dict) -> bool:
    """True when `.env` carries a non-empty key for the provider.

    Anonymous tiers (`required=False`) still need a key here: an empty
    `api_key` is rejected by the OpenAI client inside LiteLLM before the
    request leaves, so a keyless deployment would only burn an attempt.
    """
    prov = providers.get(provider)
    return bool(prov and prov.env_var and env.get(prov.env_var))


def chain(blocks: list[dict], env: dict[str, str], providers: dict | None = None) -> list[dict]:
    """Ordered, de-duplicated chat deployments that have a key in `env`.

    `blocks` are parse_blocks() dicts (rendered or template). Order is
    provider priority first, then template order; the first occurrence of
    a backend wins when several aliases point at it.
    """
    if providers is None:
        from providers_config import PROVIDERS
        providers = PROVIDERS
    picked: list[tuple[int, int, dict]] = []
    seen: set[tuple[str, str]] = set()
    for pos, b in enumerate(blocks):
        if b.get("mode", "chat") != "chat" or not b.get("provider"):
            continue
        if not has_key(b["provider"], env, providers):
            continue
        key = deployment_key(b)
        if key in seen:
            continue
        seen.add(key)
        picked.append((_RANK.get(b["provider"], len(_RANK)), pos, b))
    picked.sort(key=lambda t: (t[0], t[1]))
    return [b for _, _, b in picked]


def _body(block: dict) -> list[str]:
    """Block lines without the model_name line and without the trailing
    blank/comment lines that parse_blocks attributes to the block (they
    are the next block's header)."""
    lines = block["lines"][1:]
    while lines and (not lines[-1].strip() or lines[-1].strip().startswith("#")):
        lines.pop()
    return lines


def render_blocks(chain_blocks: list[dict]) -> list[str]:
    """YAML lines for the `standard` deployments, ready to append to model_list."""
    if not chain_blocks:
        return []
    out: list[str] = [
        "\n",
        "  # ===========================================================================\n",
        f"  # {ROUTE_NAME}  –  every keyed chat deployment, tried in `order`\n",
        "  # (generated by fork/render.py; see docs/adr/0001-fork-conventions.md)\n",
        "  # ===========================================================================\n",
    ]
    for n, b in enumerate(chain_blocks, start=1):
        out.append("\n")
        out.append(f"  - model_name: {ROUTE_NAME}\n")
        for line in _body(b):
            out.append(line if line.endswith("\n") else line + "\n")
            if line.strip() == "litellm_params:":
                out.append(f"      order: {n}\n")
    return out
